# Generated by Django 2.1.15 on 2020-01-14 03:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mae_sala',
            fields=[
                ('msl_id', models.AutoField(primary_key=True, serialize=False)),
                ('msl_nombre', models.CharField(max_length=100)),
                ('msl_numero', models.IntegerField()),
                ('msl_activa', models.BooleanField(default=True)),
                ('msl_descripción', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='nub_arrendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nrr_fecha', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ref_comuna',
            fields=[
                ('rcm_id', models.AutoField(primary_key=True, serialize=False)),
                ('rcm_nombre', models.CharField(max_length=100)),
                ('rcm_id_regiones', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ref_region',
            fields=[
                ('rrg_id', models.AutoField(primary_key=True, serialize=False)),
                ('rrg_nombre', models.CharField(max_length=100)),
                ('rrg_ordinal', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='nub_arrendar',
            name='nrr_id_comuna',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Reserva.ref_comuna'),
        ),
        migrations.AddField(
            model_name='nub_arrendar',
            name='nrr_id_region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Reserva.ref_region'),
        ),
        migrations.AddField(
            model_name='nub_arrendar',
            name='nrr_id_sala',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Reserva.mae_sala'),
        ),
    ]
