# Generated by Django 2.1.15 on 2020-01-13 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ref_comunas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('ordinal', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ref_regiones',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('ordinal', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='ref_comunas',
            name='id_ref_regiones',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Id_regiones', to='Reserva.ref_regiones'),
        ),
    ]
