# Generated by Django 2.1.15 on 2020-01-14 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reserva', '0001_initial'),
    ]

    operations = [
    ]
