# Generated by Django 2.1.15 on 2020-01-14 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reserva', '0003_auto_20200114_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mae_sala',
            name='msl_numero',
            field=models.CharField(max_length=3),
        ),
    ]
