# Generated by Django 2.1.15 on 2020-01-15 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reserva', '0004_auto_20200114_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nub_arrendar',
            name='nrr_id_comuna',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='nub_arrendar',
            name='nrr_id_region',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='nub_arrendar',
            name='nrr_id_sala',
            field=models.IntegerField(),
        ),
    ]
